Document: ravada
Title: Debian ravada Manual
Author: <insert document author here>
Abstract: This manual describes what ravada is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/ravada/ravada.sgml.gz

Format: postscript
Files: /usr/share/doc/ravada/ravada.ps.gz

Format: text
Files: /usr/share/doc/ravada/ravada.text.gz

Format: HTML
Index: /usr/share/doc/ravada/html/index.html
Files: /usr/share/doc/ravada/html/*.html
