#!/bin/sh

echo "config ravada"
# Exit on error
set -e

# Source debconf library.
. /usr/share/debconf/confmodule

# Ask questions
db_input low ravada/database_user || true
db_input low ravada/database_password || true

# Show interface
dbc_go || true
