#!/bin/bash
set -e

. /usr/share/debconf/confmodule

adduser --system --group --disabled-password --disabled-login --no-create-home --home /nonexistent ravada

if [ ! -d /var/run/ravada ]; then
    mkdir /var/run/ravada
fi
chown ravada /var/run/ravada
chmod go-rx /var/run/ravada

systemctl daemon-reload

# Configure database
dbc_mysql_createdb_encoding="UTF8"

if ! dbc_go portal3 $@ ; then
    echo 'Automatic configuration using dbconfig-db_version 2.0common failed!'
fi

